### ISSUE TITLE
What is the approximate number of gpus and total time used for training?

### ISSUE THREAD

**Issue by daifan2000** [AIR-DISCOVER/LODE#2]
Hello, now I am learning about this direction. After reading this paper, I would like to ask how many gpus you used for training, what type of gpu is it,and how much time is required for all training? Could you please tell me, thank you!

**Comment by Philipflyg** [comment]
Thank you for your interest in our work！
For scene completion, we use 6 NVIDIA GeForce RTX 3090 for training. Training time is around 10 hours for 100 epoch on the SemanticKITTI dataset (3834 training samples).
